// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Context;

namespace Project.Context.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20230510145648_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Repository.Entities.CoronaDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateOfPositiveResult")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfRecovery")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstProducer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstVaccination")
                        .HasColumnType("datetime2");

                    b.Property<string>("FourthProducer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FourthVaccination")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondProducer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SecondVaccination")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThreeProducer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThreeVaccination")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("coronaDetailss");
                });

            modelBuilder.Entity("Project.Repository.Entities.PersonalDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNum")
                        .HasColumnType("int");

                    b.Property<string>("Tz")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("personalDetailss");
                });
#pragma warning restore 612, 618
        }
    }
}
